// DefendITC Knowledge Base — 75 court judgments + 12 CBIC circulars
// Last updated: 2026-04-30

// Data Storage
        window._ALL_CASES = [
            {
                number: "01",
                title: "M/s High Tech Ecogreen Contractors LLP v. Joint Director, DGGI",
                court: "Assam HC",
                courtFull: "Assam-High Court",
                tier: "High Courts",
                date: "25022025",
                outcome: "Department Won",
                provision: "Rule 36(4)",
                courtType: "HC",
                category: "Cat 1",
                denialCategory: "GSTR-2A/2B Mismatch",
                pdfUrl: "https://drive.google.com/file/d/1ja32L76eFQ8gYAckypPiJvBJleX3fPUD/preview",
                citation: "WP(C)/4787/2024"
            },
            {
                number: "02",
                title: "Bharat Aluminium Company Ltd. v. Union of India",
                court: "Chattisgarh HC",
                courtFull: "Chattisgarh-High Court",
                tier: "High Courts",
                date: "24062021",
                outcome: "Taxpayer Won",
                provision: "Rule 36(4)",
                courtType: "HC",
                category: "Cat 2",
                denialCategory: "GSTR-2A/2B Mismatch",
                pdfUrl: "https://drive.google.com/file/d/1K_6AdY1pycAX-GuVrO6tcGTgY-7nMMov/preview",
                citation: "WPT No. 94/2021"
            },
            {
                number: "03",
                title: "Nahasshukoor v. Assistant Commissioner",
                court: "Kerala HC",
                courtFull: "Kerala High Court",
                tier: "High Courts",
                date: "03112023",
                outcome: "Department Won",
                provision: "Rule 36(4)",
                courtType: "HC",
                category: "Cat 1",
                denialCategory: "GSTR-2A/2B Mismatch",
                pdfUrl: "https://drive.google.com/file/d/1qCWD0ynzbqZNev3xdzzd5bT_wI8TrS_0/preview",
                citation: "WA No. 1853 of 2023"
            },
            {
                number: "04",
                title: "Rubicon Associates v. State Tax Officer",
                court: "Madras HC",
                courtFull: "Madras High Court",
                tier: "High Courts",
                date: "06012026",
                outcome: "Taxpayer Won",
                provision: "Rule 36(4)",
                courtType: "HC",
                category: "Procedural Defect",
                denialCategory: "GSTR-2A/2B Mismatch",
                pdfUrl: "https://drive.google.com/file/d/1eAlfbE-Ms1djDHChOHy7jSluJbLFzBx6/preview",
                citation: "WP No. 50214/2025"
            },
            {
                number: "05",
                title: "L&T Geostructure LLP v. Union of India",
                court: "Madras HC",
                courtFull: "Madras High Court",
                tier: "High Courts",
                date: "09052025",
                outcome: "Department Won",
                provision: "Rule 36(4)",
                courtType: "HC",
                category: "Cat 1",
                denialCategory: "GSTR-2A/2B Mismatch",
                pdfUrl: "https://drive.google.com/file/d/1dQCT5oSP8LY8qbc4I--njpVK_N8Wd7nY/preview",
                citation: "W.P.Nos.5978 and 5983 of 2020"
            },
            {
                number: "06",
                title: "M/s Baby Marine (Eastern) Exports vs. Union of India & Others",
                court: "Madras HC(Madurai Bench)",
                courtFull: "Madras High Court(Madurai Bench)",
                tier: "High Courts",
                date: "06082025",
                outcome: "Department Won",
                provision: "Rule 36(4)",
                courtType: "HC",
                category: "Cat 1",
                denialCategory: "GSTR-2A/2B Mismatch",
                pdfUrl: "https://drive.google.com/file/d/1QcnO-LKcSryQwIQANQKOnZ_RCCO8fC-r/preview",
                citation: "Writ Petition No. 21165 & 21166 of 2022"
            },
            {
                number: "07",
                title: "M/s Abhimaani Structures v. Superintendent of Central Tax",
                court: "Karnataka HC @ Bengaluru Bench",
                courtFull: "Karnataka High Court @ Bengaluru Bench",
                tier: "High Courts",
                date: "28112025",
                outcome: "Taxpayer Won",
                provision: "Rule 36(4)",
                courtType: "HC",
                category: "Cat 3",
                denialCategory: "GSTR-2A/2B Mismatch",
                pdfUrl: "https://drive.google.com/file/d/18uGVnhKhOhf0qfKGpAYaicOh4fG07sat/preview",
                citation: "W.P. No. 35021/2025"
            },
            {
                number: "08",
                title: "Guru Mahesh Medicals v. Assistant Commissioner",
                court: "Karnataka HC @ Bengaluru Bench",
                courtFull: "Karnataka High Court @ Bengaluru Bench",
                tier: "High Courts",
                date: "08102025",
                outcome: "Taxpayer Won",
                provision: "Rule 36(4)",
                courtType: "HC",
                category: "Cat 3",
                denialCategory: "GSTR-2A/2B Mismatch",
                pdfUrl: "https://drive.google.com/file/d/1NeaENekRPWdLgbnLDg-bBUlIg7ZVM42p/preview",
                citation: "WP 29754/2025"
            },
            {
                number: "09",
                title: "Karibasappa Durgappa Hadagali v. GST Authorities",
                court: "High Court of Karnataka at Dharwad",
                courtFull: "High Court of Karnataka at Dharwad",
                tier: "High Courts",
                date: "24112025",
                outcome: "Taxpayer Won",
                provision: "Rule 36(4)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1DQAZwmlBcC0HXUsjK2op-JE4s9X8Klk4/preview",
                citation: "W.P. No. 108748/2025"
            },
            {
                number: "10",
                title: "R.S. Marketing and Logistics Private Limited v. Commercial Tax Officer",
                court: "Karnataka HC @ Bengaluru Bench",
                courtFull: "Karnataka High Court @ Bengaluru Bench",
                tier: "High Courts",
                date: "05062024",
                outcome: "Taxpayer Won",
                provision: "Rule 36(4)",
                courtType: "HC",
                category: "Cat 3",
                denialCategory: "GSTR-2A/2B Mismatch",
                pdfUrl: "https://drive.google.com/file/d/1_XmjxmZl-1xHnCbrlqxFMPXlEGX699tS/preview",
                citation: "WP No. 7295/2024"
            },
            {
                number: "11",
                title: "AMIT JASRASARIA vs. THE UNION OF INDIA AND 4 ORS",
                court: "Gauhati HC",
                courtFull: "Gauhati High Court",
                tier: "High Courts",
                date: "03102024",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "HC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1JuFZmFfYp0UhNKFHDOpym7VWD0HIJUoG/preview",
                citation: "WP(C)/2251/2024"
            },
            {
                number: "12",
                title: "BBA Infrastructure Ltd. v. Senior Joint Commissioner of State Tax",
                court: "Calcutta HC",
                courtFull: "Calcutta High Court",
                tier: "High Courts",
                date: "13122023",
                outcome: "Department Won",
                provision: "Section 16(4)",
                courtType: "HC",
                category: "Cat 1",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/10nQq54Y48Mc6SGb7GaKyhQAUiHu_S9M_/preview",
                citation: "MAT No. 1099 of 2023"
            },
            {
                number: "13",
                title: "Challiyil_Vijayan_Shan_vs_Assistant_Commissioner_Wc_Lt_on_4_June_2024",
                court: "Kerala HC",
                courtFull: "Kerala High Court",
                tier: "High Courts",
                date: "04062024",
                outcome: "Department Won",
                provision: "Section 16(4)",
                courtType: "HC",
                category: "Cat 2",
                denialCategory: "GSTR-2A/2B Mismatch",
                pdfUrl: "https://drive.google.com/file/d/1HW4ehryUy4tX0w_IGB752jazj9vA2sPk/preview",
                citation: "WP(C) No. 24677 of 2023"
            },
            {
                number: "14",
                title: "Gobinda Construction & Ors. vs UOI 2023-VIL-623-PAT",
                court: "Patna HC",
                courtFull: "Patna High Court",
                tier: "High Courts",
                date: "08092023",
                outcome: "Department Won",
                provision: "Section 16(4)",
                courtType: "HC",
                category: "Cat 1",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/16Yg2cz18Wa4qP2hAOVJIz5G0IWvv0VlP/preview",
                citation: "Civil Writ Jurisdiction Case No. 9108 of 2021 (2023-VIL-623-PAT)"
            },
            {
                number: "15",
                title: "M_S_Anthikad_Service_Co_Operative_vs_Union_Of_India_on_21_August_2025",
                court: "Kerala HC",
                courtFull: "Kerala High Court",
                tier: "High Courts",
                date: "21082025",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "HC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1TwyfNOVMgK_B2nsb2Pity-iS_jiobPp6/preview",
                citation: "WP(C) No. 17520 of 2024"
            },
            {
                number: "16",
                title: "M_S_Babas_Beans_vs_Union_Of_India_Ors_on_9_July_2024",
                court: "Delhi HC",
                courtFull: "Delhi High Court",
                tier: "High Courts",
                date: "2024-07-09 00:00:00",
                outcome: "Mixed / Remanded",
                provision: "Section 16(4)",
                courtType: "HC",
                category: "Cat 2",
                denialCategory: "Time-Barred Claims",
                pdfUrl: "https://drive.google.com/file/d/1JzSYpYspE30Q3DO8Q2bGOeCrhn4-RXhp/preview",
                citation: "2024 SCC OnLine Del (W.P.(C) 9205/2024)"
            },
            {
                number: "17",
                title: "M_S_Mall_Of_Joy_Pvt_Limited_vs_Union_Of_India_on_4_June_2024",
                court: "Kerala HC",
                courtFull: "Kerala High Court",
                tier: "High Courts",
                date: "2024-06-04 00:00:00",
                outcome: "Mixed / Remanded",
                provision: "Section 16(4)",
                courtType: "HC",
                category: "Cat 2",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1XtlQ_-Tc0sfhbofWHl_ET5Ho-DHt2hFp/preview",
                citation: "2024 SCC OnLine Ker (Kerala High Court)"
            },
            {
                number: "18",
                title: "M_S_R_K_Modi_And_Sons_vs_Union_Of_India_on_20_April_2022",
                court: "Madhya Pradesh HC (Indore Bench)",
                courtFull: "Madhya Pradesh High Court (Indore Bench)",
                tier: "High Courts",
                date: "2022-04-20 00:00:00",
                outcome: "Mixed / Remanded",
                provision: "Section 16(4)",
                courtType: "HC",
                category: "Cat 1",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1KlmYoPP1tApw9wbewT9mI_PEKG2Mkrj5/preview",
                citation: "2022 SCC OnLine MP"
            },
            {
                number: "19",
                title: "M/s Jyotirmoyee Drugs & Anr. v. Union of India & Ors.",
                court: "Gauhati HC",
                courtFull: "Gauhati High Court",
                tier: "High Courts",
                date: "2024-06-27 00:00:00",
                outcome: "Mixed / Remanded",
                provision: "Section 16(4)",
                courtType: "HC",
                category: "Cat 2",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1Vta2CL6kVFVGAGLF8HLT1-fbqMEQSODq/preview",
                citation: "2024 SCC OnLine Gauhati (WP(C) 3287/2024)"
            },
            {
                number: "20",
                title: "Puthanangadi_Industries_vs_The_State_Of_Kerala_on_4_June_2024",
                court: "Kerala HC",
                courtFull: "Kerala High Court",
                tier: "High Courts",
                date: "2024-06-04 00:00:00",
                outcome: "Mixed / Remanded",
                provision: "Section 16(4)",
                courtType: "HC",
                category: "Cat 1",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/13U6deJ5KivpCG1IiLM4Pr7-tmDfT0b5s/preview",
                citation: "2024 SCC OnLine Ker"
            },
            {
                number: "21",
                title: "Salahudheen_vs_State_Tax_Officer_on_4_June_2024",
                court: "High Court of Kerala",
                courtFull: "High Court of Kerala",
                tier: "High Courts",
                date: "2024-06-04 00:00:00",
                outcome: "Department Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 2",
                denialCategory: "GSTR-2A/2B Mismatch",
                pdfUrl: "https://drive.google.com/file/d/1-V4NZ1ermAd1GYiFvpIvSRj5sAxCd2Jm/preview",
                citation: "WP (C) NO. 25891 OF 2020"
            },
            {
                number: "22",
                title: "Ultraprime_Cements_India_Pvt_Ltd_vs_Central_Board_Of_Indirect_Taxes_And_on_4_June_2024",
                court: "High Court of Kerala",
                courtFull: "High Court of Kerala",
                tier: "High Courts",
                date: "2024-06-04 00:00:00",
                outcome: "Department Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 1",
                denialCategory: "GSTR-2A/2B Mismatch",
                pdfUrl: "https://drive.google.com/file/d/1E27HFKAN9sFQF_oqAa2ZtUl3k5JZgRqO/preview",
                citation: "WP (C) NO. 31559 OF 2019"
            },
            {
                number: "23",
                title: "Yohanan_Thyparampil_Easow_vs_State_Tax_Officer_on_4_June_2024",
                court: "High Court of Kerala",
                courtFull: "High Court of Kerala",
                tier: "High Courts",
                date: "2024-06-04 00:00:00",
                outcome: "Department Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 1",
                denialCategory: "Time-Barred Claims",
                pdfUrl: "https://drive.google.com/file/d/1iFEAMXKDbeG_wNDLph4Bb-lgVrEZJIPx/preview",
                citation: "WP (C) NO. 26515 OF 2021"
            },
            {
                number: "24",
                title: "Anand Steel vs. Union of India and Others",
                court: "High Court of Madhya Pradesh",
                courtFull: "High Court of Madhya Pradesh",
                tier: "High Courts",
                date: "November 22, 2024",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1gy4__EjH9AC7KHrfBBSU8qbWA2tySoE7/preview",
                citation: "Neutral Citation No. 2024:MPHC-IND:32971."
            },
            {
                number: "25",
                title: "Dys_Impex_Private_Limited_vs_Assistant_Commissioner_Of_Revenue_on_25_June_2025",
                court: "High Court at Calcutta.",
                courtFull: "High Court at Calcutta.",
                tier: "High Courts",
                date: "June 25, 2025",
                outcome: "Mixed / Remanded",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1i_zL8LMEqGtFdVEN6O707nrkphiOISoA/preview",
                citation: "WPA 2980 of 2025."
            },
            {
                number: "26",
                title: "M_S_Abdul_Parvej_Khan_Contractor_Trade_vs_Union_Of_Inida_Through_The_Central_Board_on_22_November_2024",
                court: "High Court of Madhya Pradesh",
                courtFull: "High Court of Madhya Pradesh",
                tier: "High Courts",
                date: "2024-11-22 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1x745hDiTq8HUqY4D2nCenz-du4sTdeOb/preview",
                citation: "MPHC-IND:32971 | WP No. 14975 of 2024"
            },
            {
                number: "27",
                title: "M_S_Selva_Vilas_Jewellery_vs_The_Superintendent_Of_Gst_And_Central_on_7_January_2026",
                court: "Madurai Bench of Madras HC",
                courtFull: "Madurai Bench of Madras High Court",
                tier: "High Courts",
                date: "2026-07-01 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "HC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1hnmnE86wWu5KjFz0vaCtFF3S-INtkfYd/preview",
                citation: "W.P.(MD) No.35289 of 2025"
            },
            {
                number: "28",
                title: "M_S_Tara_Fertilizers_Gulabbagh_Purnia_vs_The_State_Of_Bihar_on_8_September_2023 (1)",
                court: "High Court of Judicature at Patna",
                courtFull: "High Court of Judicature at Patna",
                tier: "High Courts",
                date: "2023-08-09 00:00:00",
                outcome: "Department Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 1",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1SQieacxOfpP2GR_BW7gCwrHYZvolqSLY/preview",
                citation: "CWJC No. 9108 of 2021"
            },
            {
                number: "29",
                title: "Manoj_Kumar_Singh_vs_Principal_Commissioner_on_21_January_2026",
                court: "High Court of Jharkhand",
                courtFull: "High Court of Jharkhand",
                tier: "High Courts",
                date: "21-01-2026",
                outcome: "Mixed / Remanded",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/11GRTPrSx_Av-q5xdja5F_hgNHmtxQ80G/preview",
                citation: "W.P.(T) No. 7467 of 2025"
            },
            {
                number: "30",
                title: "P_Prakash_Construction_A_Partnership_vs_Union_Of_India_on_8_September_2023",
                court: "Patna HC.",
                courtFull: "Patna High Court.",
                tier: "High Courts",
                date: "September 8, 2023",
                outcome: "Mixed / Remanded",
                provision: "Section 16(4)",
                courtType: "HC",
                category: "Cat 1",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1xAXivLJChC2yWQunQhfMZ1emN5EqIKp3/preview",
                citation: "CWJC No. 9108 of 2021."
            },
            {
                number: "31",
                title: "Pazhassi_Motors_vs_State_Of_Kerala_on_4_December_2025",
                court: "High Court of Kerala",
                courtFull: "High Court of Kerala",
                tier: "High Courts",
                date: "December 4, 2025",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1uycTESktMYscI9-WHvy0AKWFNnx8zgTj/preview",
                citation: "W.P.(C.) No. 45451 of 2025"
            },
            {
                number: "32",
                title: "Philip_Thomas_vs_State_Tax_Officer_on_27_January_2026",
                court: "High Court of Kerala",
                courtFull: "High Court of Kerala",
                tier: "High Courts",
                date: "January 27, 2026",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Time-Barred Claims",
                pdfUrl: "https://drive.google.com/file/d/12FN_A6bdIc32dexsKQPKigwov9QyFIfA/preview",
                citation: "WP (C) No.46773 of 2025"
            },
            {
                number: "33",
                title: "Tirumala Konda Plywoods vs The Assistant Commissioner",
                court: "High Court of Andhra Pradesh",
                courtFull: "High Court of Andhra Pradesh",
                tier: "High Courts",
                date: "July 18, 2023",
                outcome: "Mixed / Remanded",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 1",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1Y6Yzgbmedr1jUnZvADV4wMs1KzfI5UUh/preview",
                citation: "W.P.No.24235 of 2022."
            },
            {
                number: "34",
                title: "Tvl.Kavin HP Gas Gramin Vitrak vs The Commissioner of Commercial Taxes",
                court: "Madurai Bench of Madras HC.",
                courtFull: "Madurai Bench of Madras High Court.",
                tier: "High Courts",
                date: "November 24, 2023",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "HC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1dIWMN336jMKDU4DCEOArWRatttfSouoS/preview",
                citation: "W.P.(MD).Nos.7173 and 7174 of 2023."
            },
            {
                number: "35",
                title: "M/s D.Y. Beathel Enterprises v. State Tax Officer (Data Cell)",
                court: "Madras HC (Madurai Bench)",
                courtFull: "Madras High Court (Madurai Bench)",
                tier: "High Courts",
                date: "2021-02-24 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(2)(c)",
                courtType: "HC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/155tkUbII_covGGjWgbZMprHv8d_txIyL/preview",
                citation: "2021 SCC OnLine Mad 296; (2021) 127"
            },
            {
                number: "36",
                title: "M/s LGW Industries Ltd. & Ors. v. Union of India & Ors.",
                court: "Calcutta HC",
                courtFull: "Calcutta High Court",
                tier: "High Courts",
                date: "2021-12-13 00:00:00",
                outcome: "Mixed / Remanded",
                provision: "Section 16(2)(c)",
                courtType: "HC",
                category: "Cat 2",
                denialCategory: "Fake/Bogus Invoices",
                pdfUrl: "https://drive.google.com/file/d/1iLb2dPGI40tgMxoLwTtgDp4EiUQY2Efl/preview",
                citation: "2022 SCC OnLine Cal 112"
            },
            {
                number: "37",
                title: "Suncraft Energy Pvt. Ltd. & Anr. v. Assistant Commissioner of State Tax, Ballygunge Charge & Ors.",
                court: "Calcutta HC",
                courtFull: "Calcutta High Court",
                tier: "High Courts",
                date: "2023-08-02 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(2) CGST Act",
                courtType: "HC",
                category: "Cat 3",
                denialCategory: "GSTR-2A/2B Mismatch",
                pdfUrl: "https://drive.google.com/file/d/bc1qre8jdw2azrg6tf49wmp652w00xltddxmpk98xp/preview",
                citation: "2023 SCC OnLine Cal 2685; (2023) 153"
            },
            {
                number: "38",
                title: "Sanchita Kundu & Anr. v. Assistant Commissioner of State Tax, Bureau of Investigation, South Bengal & Ors",
                court: "Calcutta HC",
                courtFull: "Calcutta High Court",
                tier: "High Courts",
                date: "2022-05-05 00:00:00",
                outcome: "Mixed / Remanded",
                provision: "Section 16 CGST Act",
                courtType: "HC",
                category: "Cat 2",
                denialCategory: "Fake/Bogus Invoices",
                pdfUrl: "https://drive.google.com/file/d/bc1qre8jdw2azrg6tf49wmp652w00xltddxmpk98xp/preview",
                citation: "2022 (63) G.S.T.L. 413 (Cal.)"
            },
            {
                number: "39",
                title: "M/S R.T. Infotech v. Additional Commissioner Grade-2 & Others",
                court: "Allahabad HC",
                courtFull: "Allahabad High Court",
                tier: "High Courts",
                date: "2025-05-30 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(2)(c)",
                courtType: "HC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/bc1qre8jdw2azrg6tf49wmp652w00xltddxmpk98xp/preview",
                citation: "Writ Tax No. 1330 of 2022"
            },
            {
                number: "40",
                title: "Lokenath Construction Pvt. Ltd. v. Joint Commissioner of State Tax / Union of India & Ors",
                court: "Calcutta HC",
                courtFull: "Calcutta High Court",
                tier: "High Courts",
                date: "2024-05-02 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(2)(c)",
                courtType: "HC",
                category: "Cat 3",
                denialCategory: "GSTR-2A/2B Mismatch",
                pdfUrl: "https://drive.google.com/file/d/1odF7k2CrM41_N5BkXMPNG3Mh-i1wwTgh/preview",
                citation: "MAT 2459 of 2023 with WPA 5222 of 2024"
            },
            {
                number: "41",
                title: "M/S Shree Kishna Chemicals v. Union of India & Ors.",
                court: "Madhya Pradesh HC",
                courtFull: "Madhya Pradesh High Court",
                tier: "High Courts",
                date: "2025-02-17 00:00:00",
                outcome: "Department Won",
                provision: "Section 16(2)(c)",
                courtType: "HC",
                category: "Cat 2",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1Dquh2m_opTWEiCpdzdPnHqV8D3zYPVYK/preview",
                citation: "Writ Petition (Civil) No. 10973 of 2024"
            },
            {
                number: "42",
                title: "M/s Aastha Enterprises v. State of Bihar & Ors",
                court: "Patna HC",
                courtFull: "Patna High Court",
                tier: "High Courts",
                date: "2023-08-18 00:00:00",
                outcome: "Department Won",
                provision: "Section 16(2)(c)",
                courtType: "HC",
                category: "Cat 1",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1bMEckcxTvgh_-6v4EiwcYEetp-tNvaA_/preview",
                citation: "Civil Writ Jurisdiction Case No. 10395 of 2023"
            },
            {
                number: "43",
                title: "Trendships Online Services Pvt. Ltd. v. Commissioner, Commercial Taxes U.P. & Anr",
                court: "Allahabad HC",
                courtFull: "Allahabad High Court",
                tier: "High Courts",
                date: "2025-05-26 00:00:00",
                outcome: "Department Won",
                provision: "Section 16(2)(c)",
                courtType: "HC",
                category: "Cat 1",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/bc1qre8jdw2azrg6tf49wmp652w00xltddxmpk98xp-E9/preview",
                citation: "Writ Tax No. 501 of 2023"
            },
            {
                number: "44",
                title: "Commissioner of Trade & Taxes, Delhi v. M/s Shanti Kiran India Pvt. Ltd.",
                court: "Supreme Court of India",
                courtFull: "Supreme Court of India",
                tier: "Supreme Court of India",
                date: "2025-10-09 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(2)(c)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1m6GfSuIT1vvIjmSJa6z0sFkoM9f8L70X/preview",
                citation: "2025 VIL 83 SC"
            },
            {
                number: "45",
                title: "On Quest Merchandising India Pvt. Ltd. v. Government of NCT of Delhi & Ors.",
                court: "Delhi HC",
                courtFull: "Delhi High Court",
                tier: "High Courts",
                date: "2017-10-26 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(2)(c)",
                courtType: "HC",
                category: "Cat 3",
                denialCategory: "GSTR-2A/2B Mismatch",
                pdfUrl: "https://drive.google.com/file/d/1iZRyIHJXCMiHXGIoWGN7UBcTuejrKKVz/preview",
                citation: "W.P.(C) 6093/2017"
            },
            {
                number: "46",
                title: "Sahil Enterprises v. Union of India & Ors.",
                court: "Tripura HC",
                courtFull: "Tripura High Court",
                tier: "High Courts",
                date: "2026-01-07 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(2)(c)",
                courtType: "HC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1cnDR9yKYpM_yOUQPPnuY_9RX6OV9UyAu/preview",
                citation: "WP(C) 688 of 2022"
            },
            {
                number: "47",
                title: "Arise India Limited v. Commissioner of Trade & Taxes, Delhi",
                court: "Delhi HC",
                courtFull: "Delhi High Court",
                tier: "High Courts",
                date: "2017-10-26 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(2)(c)",
                courtType: "HC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1Khluu8RWvUhom2NOM-cGAbvNOrY2-R-X/preview",
                citation: "W.P.(C) 2106/2015 & batch"
            },
            {
                number: "48",
                title: "Diya Agencies v. State Tax Officer (Data Cell), State GST Department & Ors.",
                court: "High Court of Kerala at Ernakulam",
                courtFull: "High Court of Kerala at Ernakulam",
                tier: "High Courts",
                date: "2023-09-12 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(2)(c)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "GSTR-2A/2B Mismatch",
                pdfUrl: "https://drive.google.com/file/d/1oe1pI-q9Xl5giKjIbPUKa5XBnFCL4ps8/preview",
                citation: "2023:KER:55318"
            },
            {
                number: "49",
                title: "Tashi Air Pvt. Ltd. v. Union of India & Ors",
                court: "Gauhati HC",
                courtFull: "Gauhati High Court",
                tier: "High Courts",
                date: "2024-08-05 00:00:00",
                outcome: "Department Won",
                provision: "Section 16(2)(c)",
                courtType: "HC",
                category: "Cat 1",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1UvrX4SLLpGkZHPmyQNecJsRalWxYWkTm/preview",
                citation: "2024 SCC OnLine Gau 1595"
            },
            {
                number: "50",
                title: "Sri Ganapathi Pandi Industries & Batch vs. The Assistant Commissioner (State Tax)",
                court: "High Court of Judicature at Madras",
                courtFull: "High Court of Judicature at Madras",
                tier: "High Courts",
                date: "2024-10-17 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1Ik1WFYNhl_lVfLLgo8gbN5NZDdjKEJuQ/preview",
                citation: "W.P.No.25081 of 2023 & connected WPs"
            },
            {
                number: "51",
                title: "Philip Thomas vs. State Tax Officer, SGST Department & Ors.",
                court: "High Court of Kerala at Ernakulam",
                courtFull: "High Court of Kerala at Ernakulam",
                tier: "High Courts",
                date: "2026-01-27 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1yoNytIR5pmuljB0ziuViRcg60vdn3WZ1/preview",
                citation: "WP(C) No.46773 of 2025"
            },
            {
                number: "52",
                title: "Pazhassi Motors vs. State of Kerala & Ors.",
                court: "High Court of Kerala at Ernakulam",
                courtFull: "High Court of Kerala at Ernakulam",
                tier: "High Courts",
                date: "2025-12-04 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1X3SMmvMRLdJlMdbNhbOWr_dHCZER5ZPS/preview",
                citation: "WP(C) No.45451 of 2025"
            },
            {
                number: "53",
                title: "M/s Sesame Technologies Pvt. Ltd. vs. Deputy State Tax Officer & Anr.",
                court: "High Court of Kerala at Ernakulam",
                courtFull: "High Court of Kerala at Ernakulam",
                tier: "High Courts",
                date: "2026-01-06 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1X3SMmvMRLdJlMdbNhbOWr_dHCZER5ZPS/preview",
                citation: "WP(C) No.48616 of 2025"
            },
            {
                number: "54",
                title: "Prabir Kumar Das vs. Assistant Commissioner of State Tax, Bureau of Investigation (North Bengal) Raiganj Zone & Ors.",
                court: "High Court of Calcutta",
                courtFull: "High Court of Calcutta",
                tier: "High Courts",
                date: "2025-03-05 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1S4gdj5CbvhJTzPXWzpZfEGsrIxLGBaZn/preview",
                citation: "WPA 21120 of 2021 (Calcutta High Court)"
            },
            {
                number: "55",
                title: "Med Biogenex Private Limited vs. Superintendent, Central Goods & Services Tax & Central Excise, Range-VII, BBD Bag-II & Ors.",
                court: "High Court of Calcutta",
                courtFull: "High Court of Calcutta",
                tier: "High Courts",
                date: "2025-03-05 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1rkCxmwyDI04pin0CRjBlQngTn-bvfwiK/preview",
                citation: "WPA 19986 of 2024"
            },
            {
                number: "56",
                title: "Hiranmoy Dutta vs. The State of West Bengal",
                court: "High Court of Calcutta",
                courtFull: "High Court of Calcutta",
                tier: "High Courts",
                date: "2025-03-06 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/18e06QY94D8OWaABSkrd2_mOWAjttb8j5/preview",
                citation: "WPA 13453 of 2024 (Calcutta High Court)"
            },
            {
                number: "57",
                title: "Rajkumar Josphine vs. Superintendent, Ministry of Finance / Department of Revenue",
                court: "High Court of Judicature at Madras",
                courtFull: "High Court of Judicature at Madras",
                tier: "High Courts",
                date: "2025-07-09 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/17klIh-oYUJTmVTL0UvRK5EbRf-rTokGR/preview",
                citation: "2025 SCC OnLine Mad 3242"
            },
            {
                number: "58",
                title: "M/s McLeod Russel India Limited vs. The Union of India",
                court: "Gauhati HC — Division Bench",
                courtFull: "Gauhati High Court — Division Bench",
                tier: "High Courts",
                date: "2025-12-09 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(2)(aa)",
                courtType: "HC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/117krGPvEjUSZWtT6vl4t65KFAmlcI9wE/preview",
                citation: "WP(C) No.5725 of 2022"
            },
            {
                number: "59",
                title: "B. Braun Medical India Pvt. Ltd. vs. Union of India & Ors.",
                court: "High Court of Delhi",
                courtFull: "High Court of Delhi",
                tier: "High Courts",
                date: "2025-03-12 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(2)(aa)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1t4aisP7NL_H2cNOcOJC4Wa0bshLmnNca/preview",
                citation: "W.P.(C) 114/2025"
            },
            {
                number: "60",
                title: "M. Trade Links vs. Union of India & Ors.",
                court: "High Court of Kerala",
                courtFull: "High Court of Kerala",
                tier: "High Courts",
                date: "4 Jume 2024",
                outcome: "Taxpayer Won",
                provision: "Section 16(2)(c)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/bc1qre8jdw2azrg6tf49wmp652w00xltddxmpk98xp/preview",
                citation: "2024 SCC OnLine Ker 2744"
            },
            {
                number: "61",
                title: "Bharti Telemedia Ltd. v. Union of India & Ors.",
                court: "High Court of Delhi",
                courtFull: "High Court of Delhi",
                tier: "High Courts",
                date: "Ongoing (Sub-judice) The latest major procedural order was passed on February 19, 2025,",
                outcome: "Department Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 2",
                denialCategory: "GSTR-2A/2B Mismatch",
                pdfUrl: "https://drive.google.com/file/d/1qtMRAJbMkrqz2QWP3-nxCVe_8AR5uY3h/preview",
                citation: "W.P.(C) 6293/2019"
            },
            {
                number: "62",
                title: "Manoj Kumar Singh v. Principal Commissioner, CGST & Central Excise and Another",
                court: "High Court of Jharkhand at Ranchi",
                courtFull: "High Court of Jharkhand at Ranchi",
                tier: "High Courts",
                date: "2026-01-21 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/15PcOn--Xp0u_6bBkJmuOafGMj9ASlMXE/preview",
                citation: "2026 SCC OnLine Jhar 84"
            },
            {
                number: "63",
                title: "M/s. Engineering Tools Corporation vs. The Assistant Commissioner (ST), Broadway Assessment Circle",
                court: "High Court of Judicature at Madras",
                courtFull: "High Court of Judicature at Madras",
                tier: "High Courts",
                date: "2024-02-15 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(2) of the CGST/TNGS",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/bc1qre8jdw2azrg6tf49wmp652w00xltddxmpk98xp/preview",
                citation: "Writ Petition No.3505 of 2024"
            },
            {
                number: "64",
                title: "Treco Wire India Pvt. Ltd. through its Director v. The Commissioner of Central Goods and Service Tax and Ors.",
                court: "High Court of Delhi",
                courtFull: "High Court of Delhi",
                tier: "High Courts",
                date: "2025-09-24 00:00:00",
                outcome: "Mixed / Remanded",
                provision: "Section 16(2)(c)",
                courtType: "SC",
                category: "Cat 1",
                denialCategory: "Fake/Bogus Invoices",
                pdfUrl: "https://drive.google.com/file/d/1RPXa5jzXZ1kNnpgahVP5DECkjPfbDID0/preview",
                citation: "W.P.(C) 14428/2025"
            },
            {
                number: "65",
                title: "Arunachala Gas Agency vs. The Assistant Commissioner of CGST and Central Excise, Madurai-II Division",
                court: "",
                courtFull: "",
                tier: "Supreme Court of India",
                date: "2026-01-28 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/13hNHlrEX4_MUiHfsNlahXB-rX3wFnQIG/preview",
                citation: "High Court of Judicature at Madras (Madurai Bench)"
            },
            {
                number: "66",
                title: "Malaya Rub-Tech Industries v. Union of India",
                court: "High Court of Tripura at Agartala",
                courtFull: "High Court of Tripura at Agartala",
                tier: "High Courts",
                date: "2026-02-10 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(2)(c)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1Jnofk9y_S4N6xRg6844b2JTqOvHX9vGc/preview",
                citation: "2026 SCC OnLine Tri 87"
            },
            {
                number: "67",
                title: "M/S Balaji Exim vs Commissioner, CGST And Ors.",
                court: "High Court of Delhi",
                courtFull: "High Court of Delhi",
                tier: "High Courts",
                date: "2023-03-10 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(2) (Conditions for ",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Fake/Bogus Invoices",
                pdfUrl: "https://drive.google.com/file/d/1nmPXb-qB2aQhmed5cTQFykkVPj5nOi0o/preview",
                citation: "W.P. (C) 10407/2022"
            },
            {
                number: "68",
                title: "TVL. Cleon Optobiz Pvt. Ltd. vs. The Assistant Commissioner (ST), Kothawalchavadi Assessment Circle & Anr.",
                court: "High Court of Judicature at Madras",
                courtFull: "High Court of Judicature at Madras",
                tier: "High Courts",
                date: "2024-01-19 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16 of the TNGST Act",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1-vxepgek_R43JHiY2T6AGvExXV7XpiKK/preview",
                citation: "Writ Petition No. 495 of 2024"
            },
            {
                number: "69",
                title: "M/s. Asian Lifts and Escalator Private Limited vs. Assistant Commissioner of CGST & Central Excise, Porur Division",
                court: "High Court of Judicature at Madras",
                courtFull: "High Court of Judicature at Madras",
                tier: "High Courts",
                date: "2026-02-06 00:00:00",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "SC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/bc1qre8jdw2azrg6tf49wmp652w00xltddxmpk98xp/preview",
                citation: "W.P.No.2296 of 2026"
            },
            {
                number: "70",
                title: "Mahadeo Construction Co vs. The Union of India and Others",
                court: "High Court of Jharkhand",
                courtFull: "High Court of Jharkhand",
                tier: "High Courts",
                date: "21st April, 2020",
                outcome: "Taxpayer Won",
                provision: "Section 73 of CGST Act",
                courtType: "SC",
                category: "Procedural Defect",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1aA8H0IW9y6KgRrAm6Q2tv3tUw9fhg8j_/preview",
                citation: "W.P.(T) No. 3517 of 2019"
            },
            {
                number: "71",
                title: "Ashika Business Pvt Ltd vs Union of India",
                court: "Gauhati HC",
                courtFull: "Gauhati High Court",
                tier: "High Courts",
                date: "09052024",
                outcome: "Mixed / Remanded",
                provision: "Section 73 of CGST Act",
                courtType: "HC",
                category: "Cat 1",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1nszTf8EhjlUFV2HJHCQ5g7xtfIxJa5Fk/preview",
                citation: "WP(C) 2364/2024"
            },
            {
                number: "72",
                title: "Delhi Soccer Pvt. Ltd. vs Union of India",
                court: "Delhi HC",
                courtFull: "Delhi High Court",
                tier: "High Courts",
                date: "28052024",
                outcome: "Taxpayer Won",
                provision: "Section 73 of CGST Act",
                courtType: "HC",
                category: "Procedural Defect",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1ASHvGgcYGrvMaV7oKnUvjvce-BvIMkRe/preview",
                citation: "W.P.(C) 7804/2024"
            },
            {
                number: "73",
                title: "Garg Associates vs State of Assam",
                court: "Gauhati HC",
                courtFull: "Gauhati High Court",
                tier: "High Courts",
                date: "13032026",
                outcome: "Taxpayer Won",
                provision: "Section 73 of CGST Act",
                courtType: "HC",
                category: "Procedural Defect",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1a2EVP-payZiazclZIE7NilJ0ccEnz4ih/preview",
                citation: "WP(C)/1450/2026"
            },
            {
                number: "74",
                title: "Medizen Labs Private Limited vs Assistant Commissioner",
                court: "Karnataka HC",
                courtFull: "Karnataka High Court",
                tier: "High Courts",
                date: "25022026",
                outcome: "Taxpayer Won",
                provision: "Section 73 of CGST Act",
                courtType: "HC",
                category: "Procedural Defect",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1fPXk31FqpI4AwX5OWqOT3HdfDs5tgJAN/preview",
                citation: "WP No. 5225/2026"
            },
            {
                number: "75",
                title: "M/s. Rajkumar Josphine vs Superintendent",
                court: "Madras HC",
                courtFull: "Madras High Court",
                tier: "High Courts",
                date: "09072025",
                outcome: "Taxpayer Won",
                provision: "Section 16(4)",
                courtType: "HC",
                category: "Cat 3",
                denialCategory: "Other Grounds",
                pdfUrl: "https://drive.google.com/file/d/1IK8apE8hkADg9zHMREn0AI0FL2gZ4IQQ/preview",
                citation: "W.P.No.22639/2025"
            }
        ];

         window._CIRCULARS = [
            {
                number: "135/05/2020-GST",
                title: "Clarification on availment of ITC in respect of invoices/debit notes issued during FY 2017-18",
                date: "31.03.2020",
                description: "Clarifications regarding time limit for availment of ITC in respect of invoices and debit notes pertaining to FY 2017-18, considering the transitional provisions and TRAN-1/TRAN-2 filing timeline.",
                pdfUrl: "https://drive.google.com/file/d/1GPYha4pUk5YQQH2XtrGGHWVfxrk1Uwx2/preview"
            },
            {
                number: "170/02/2022-GST",
                title: "Clarification on reversal of ITC in case of non-payment to supplier",
                date: "07.02.2022",
                description: "Guidelines on reversal of input tax credit under Section 16(2)(c) when payment to supplier is not made within 180 days, including procedures for re-availment upon payment.",
                pdfUrl: "https://drive.google.com/file/d/1VP1lSZkAZgbAZleESEKpovN_q3TS5HK2/preview"
            },
            {
                number: "173/05/2022-GST",
                title: "Time limit for issuance of order under Section 73 for FY 2017-18 and 2018-19",
                date: "06.07.2022",
                description: "Extension of time limit for issuance of orders under Section 73 for financial years 2017-18 and 2018-19, considering the impact of COVID-19 pandemic on tax administration.",
                pdfUrl: "https://drive.google.com/file/d/18h9LzlZyMKquCAo0qwt_XHODvB_T6j5f/preview"
            },
            {
                number: "183/15/2022-GST",
                title: "Clarification on denial of ITC when supplier has not filed GSTR-1",
                date: "27.12.2022",
                description: "Para 5: ITC cannot be denied solely on the ground that the supplier has not filed GSTR-1, if the transaction is genuine and recipient has fulfilled all conditions under Section 16(2) of the CGST Act.",
                pdfUrl: "https://drive.google.com/file/d/1mol4EAttcKZFKqKkx4aLV86Oryc0_Zjw/preview"
            },
            {
                number: "237/31/2024-GST",
                title: "Clarification on blocking of ITC in case of mismatch between GSTR-2B and GSTR-3B",
                date: "15.08.2024",
                description: "Guidelines on reconciliation of ITC claimed in GSTR-3B vis-à-vis ITC available in GSTR-2B, procedures for claiming eligible credit, and reasons for mismatch resolution.",
                pdfUrl: "https://drive.google.com/file/d/1Nqy_PsSEwkClARXPthCHaq2j2a3PVTYc/preview"
            },
            {
                number: "238/32/2024-GST",
                title: "Procedure for claiming ITC on invoices not reflecting in GSTR-2A/2B",
                date: "30.09.2024",
                description: "Detailed procedure for claiming ITC when invoices do not reflect in GSTR-2A or GSTR-2B, documentation requirements, and communication protocol with suppliers for rectification.",
                pdfUrl: "https://drive.google.com/file/d/1KmlReT9NgAPIP-iD2Woqf6MPto2bhpIJ/preview"
            },
            {
                number: "105/24/2019-GST",
                title: "Clarification on ITC reversal under Section 17(5) - blocked credits",
                date: "28.06.2019",
                description: "Comprehensive clarification on blocked credits under Section 17(5) including credit on motor vehicles, food and beverages, outdoor catering, club/health services, and life insurance.",
                pdfUrl: "https://drive.google.com/file/d/1UgW1VqqwtzfjI8buiBlBaPbmRMU1K1Em/preview"
            },
            {
                number: "123/42/2019-GST",
                title: "Time limit for availment of Input Tax Credit under Section 16(4)",
                date: "11.11.2019",
                description: "Clarifications regarding time limit prescribed under Section 16(4) for availment of ITC - due date of filing annual return or September following the financial year, whichever is earlier. Also covers treatment of credit notes.",
                pdfUrl: "https://drive.google.com/file/d/1nIix0jJHyuMioru5z6YsgGFGDof7qAZv/preview"
            },
            {
                number: "125/44/2019-GST",
                title: "Manner of reversal of ITC in case of supply of exempted goods/services",
                date: "18.11.2019",
                description: "Guidelines on reversal of input tax credit under Section 17(2) when registered person supplies both taxable and exempted goods/services, including computation methodology under Rule 42 and Rule 43.",
                pdfUrl: "https://drive.google.com/file/d/14-R6LLo31Tw_P-yg8TUEsOUDmwB0jfeO/preview"
            },
            {
                number: "160/16/2021-GST",
                title: "Clarification on ITC in respect of demo vehicles and motor vehicles used for transportation",
                date: "20.09.2021",
                description: "Specific clarifications on availment of ITC on motor vehicles used as demo vehicles by automobile dealers and vehicles used for transportation of goods, including conditions and exceptions under Section 17(5).",
                pdfUrl: "https://drive.google.com/file/d/1OQN88bsu_1DxQTj2_Woa5x-IVTfFsjGw/preview"
            },
            {
                number: "211/5/2024-GST",
                title: "Extension of timeline for reconciliation statement in Form GSTR-2B",
                date: "15.03.2024",
                description: "Extension of timeline and clarifications regarding reconciliation statement in Form GSTR-2B, auto-population of ITC, and procedures for addressing discrepancies between supplier returns and recipient records.",
                pdfUrl: "https://drive.google.com/file/d/1rCHCMmkFz1TzZNG_pnEajBwibRhuQJpk/preview"
            },
            {
                number: "248/05/2025-GST",
                title: "Latest clarifications on E-invoice compliance and ITC eligibility",
                date: "15.01.2025",
                description: "Recent clarifications on mandatory e-invoicing requirements, impact on ITC eligibility, procedures for rectification of e-invoice errors, and transition provisions for businesses newly covered under e-invoice mandate.",
                pdfUrl: "https://drive.google.com/file/d/1E847HxC62ffR2Sfn2D5GAxNdoJpxHh5O/preview"
            }
        ];